### PR TITLE
Add ZIP and ZINB distributions

### PR DESCRIPTION
**Pull request by olivuntu**

### CODE REVIEW

**Comment by njtierney** [comment]
From https://github.com/greta-dev/greta/pull/542

Resolves #1
Resolves #2

**Comment by njtierney** [comment]
Currently it looks like there is an issue with the way the density is evaluated, perhaps something to do with the tensorflow code.

If we have this X input:

```
  [1]  87  51 140  83  34  59   0   0 106  69   0 125 104  96 145  35
 [17]  71 121  98  61 206 123 105 127  86  90  63 157  89  69  88 107
 [33] 117   0  92  97  69  53  48 109   0  93  54  93   0   0  97 157
 [49]  96   0 102 105 129  99  79   0  50  84   0 127   0   0 103   0
 [65]  93 120  63  60 114  52   0   0   0  88  83  98  93  52  98 120
 [81]  70  66  83  67 153  76   0  45   0 113 166  87 104  51  43  62
 [97]  98  75  67  62
```

Then the log density of the R function, `extraDistr::dzinb` at those values gives us:

```
  [1] -4.524637 -5.205627 -6.012118 -4.503590 -6.680826 -4.844479
  [7] -1.609438 -1.609438 -4.835701 -4.589596 -1.609438 -5.414852
 [13] -4.788711 -4.632289 -6.233713 -6.557344 -4.560018 -5.274798
 [19] -4.666421 -4.777817 -9.589039 -5.343725 -4.811833 -5.488112
 [25] -4.517716 -4.551703 -4.719461 -6.805199 -4.541652 -4.589596
 [31] -4.532623 -4.860300 -5.143829 -1.609438 -4.574781 -4.648922
 [37] -4.589596 -5.099876 -5.386202 -4.911642 -1.609438 -4.587768
 [43] -5.051086 -4.587768 -1.609438 -1.609438 -4.648922 -6.805199
 [49] -4.632289 -1.609438 -4.744757 -4.811833 -5.563442 -4.684770
 [55] -4.501207 -1.609438 -5.262786 -4.507168 -1.609438 -5.488112
 [61] -1.609438 -1.609438 -4.766347 -1.609438 -4.587768 -5.241181
 [67] -4.719461 -4.810078 -5.051929 -5.151358 -1.609438 -1.609438
 [73] -1.609438 -4.532623 -4.503590 -4.666421 -4.587768 -5.151358
 [79] -4.666421 -5.241181 -4.574004 -4.646455 -4.503590 -4.625775
 [85] -6.608828 -4.512755 -1.609438 -5.595867 -1.609438 -5.022554
 [91] -7.266722 -4.524637 -4.788711 -5.205627 -5.753569 -4.747632
 [97] -4.666421 -4.519313 -4.625775 -4.747632
```

but the greta log density is

```
 [1]       NaN       NaN       NaN       NaN       NaN       NaN
  [7] -1.609438 -1.609438       NaN       NaN -1.609438       NaN
 [13]       NaN       NaN       NaN       NaN       NaN       NaN
 [19]       NaN       NaN       NaN       NaN       NaN       NaN
 [25]       NaN       NaN       NaN       NaN       NaN       NaN
 [31]       NaN       NaN       NaN -1.609438       NaN       NaN
 [37]       NaN       NaN       NaN       NaN -1.609438       NaN
 [43]       NaN       NaN -1.609438 -1.609438       NaN       NaN
 [49]       NaN -1.609438       NaN       NaN       NaN       NaN
 [55]       NaN -1.609438       NaN       NaN -1.609438       NaN
 [61] -1.609438 -1.609438       NaN -1.609438       NaN       NaN
 [67]       NaN       NaN       NaN       NaN -1.609438 -1.609438
 [73] -1.609438       NaN       NaN       NaN       NaN       NaN
 [79]       NaN       NaN       NaN       NaN       NaN       NaN
 [85]       NaN       NaN -1.609438       NaN -1.609438       NaN
 [91]       NaN       NaN       NaN       NaN       NaN       NaN
 [97]       NaN       NaN       NaN       NaN
```

And the values that are non NaN, are the 0 values. So something is happening in the TF code, I think?

I the relevant part is:

```r
tf_distrib = function(parameters, dag) {
      size <- parameters$size
      p <- parameters$prob # probability of success
      pi <- parameters$pi
      q <- fl(1) - parameters$prob
      log_prob <- function(x) {
        tf$math$log(
          pi * tf$nn$relu(fl(1) - x) + (fl(1) - pi) * tf$pow(p, size) * tf$pow(q, x) * tf$exp(tf$math$lgamma(x + size)) / tf$exp(tf$math$lgamma(size)) / tf$exp(tf$math$lgamma(x + fl(1)))
        )
      }

    
```

**Comment by njtierney** [comment]
Ugh this could be because the `pi` symbol is overloaded and is a constant in R.

**Comment by njtierney** [comment]
OK that doesn't seem to quite be the issue, but worth checking this with @goldingn

**Comment by njtierney** [comment]
OK, trying to translate the `log_prob` function across to to R, I can get NaNs here...for values -10 and below? Seems like something strange is going on, need to have a think.

``` r
pi_var <- 0.2
p <- 0.1
q <- 1 - p
size <- 10

r_log_prob <- function(x) {
  log(
    pi_var * 
      sigmoid::relu(1 - x) + 
      (1 - pi_var) * 
      p^size * 
      q^x * 
      exp(lgamma(x + size)) / 
      exp(lgamma(size)) / 
      exp(lgamma(x + 1))
  )
}

r_log_prob(-11:10)
#>  [1]         NaN         NaN   0.6931472   0.5877867   0.4700036   0.3364722
#>  [7]   0.1823216   0.0000000  -0.2231436  -0.5108256  -0.9162907  -1.6094379
#> [13] -21.0517699 -19.4523823 -18.1714485 -17.0981540 -16.1738951 -15.3629649
#> [19] -14.6416468 -13.9932355 -13.4054489 -12.8689555
```

<sup>Created on 2022-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.0 (2022-04-22)
#>  os       macOS Big Sur/Monterey 10.16
#>  system   x86_64, darwin17.0
#>  ui       X11
#>  language (EN)
#>  collate  en_AU.UTF-8
#>  ctype    en_AU.UTF-8
#>  tz       Australia/Perth
#>  date     2022-08-02
#>  pandoc   2.17.1.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.0)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
#>  evaluate      0.15    2022-02-18 [1] CRAN (R 4.2.0)
#>  fansi         1.0.3   2022-03-24 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.0)
#>  knitr         1.39    2022-04-26 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
#>  pillar        1.8.0   2022-07-18 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.0  2022-06-28 [1] CRAN (R 4.2.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.2.0)
#>  rlang         1.0.4   2022-07-12 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.14    2022-04-25 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
#>  sigmoid       1.4.0   2022-06-18 [1] CRAN (R 4.2.0)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.2.0)
#>  styler        1.7.0   2022-03-13 [1] CRAN (R 4.2.0)
#>  tibble        3.1.7   2022-05-03 [1] CRAN (R 4.2.0)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.0)
#>  vctrs         0.4.1   2022-04-13 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.31    2022-05-10 [1] CRAN (R 4.2.0)
#>  yaml          2.3.5   2022-02-21 [1] CRAN (R 4.2.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by njtierney** [comment]
OK so I think we need to reimplement the tf log probability, using https://github.com/twolodzko/extraDistr/blob/master/src/zero-inflated-negative-binomial-distribution.cpp as a reference for the PMF

**Comment by hrlai** [comment]
> NaNs here...for values -10 and below

Seems relevant to `exp(lgamma(x + size))`. When `x` is less or equal to `-size`, `lgamma(x + size)` evaluate something less than or equal to zero and returns Inf. Because `exp(lgamma(x + 1))` also returns Inf, we end up doing Inf/Inf getting NaN... any idea where @olivuntu got the log PMF? I tried to read the forum post and the code but couldn't find a reference. But I think borrowing from `extraDistr` is a good idea too.

**Comment by hrlai** [comment]
Hang on... should we be doing ReLU of `1 - x`, or `x`? 

It's purpose is to condition on whether `x = 0` or `x > 0` right? We want to eliminate `pi_var` or the first additive term in the log PMF when `x = 0`, but if we do `relu(1 - x)` we are doing the opposite? When I change it to:
```
pi_var <- 0.2
p <- 0.1
q <- 1 - p
size <- 10

r_log_prob <- function(x) {
  log(
    pi_var * 
      sigmoid::relu(x) + 
      (1 - pi_var) * 
      p^size * 
      q^x * 
      exp(lgamma(x + size)) / 
      exp(lgamma(size)) / 
      exp(lgamma(x + 1))
  )
}
```
I get
```
> r_log_prob(-11:10)
 [1]           NaN           NaN          -Inf          -Inf          -Inf          -Inf
 [7]          -Inf          -Inf          -Inf          -Inf          -Inf -2.324899e+01
[13] -1.609438e+00 -9.162907e-01 -5.108256e-01 -2.231435e-01  9.457287e-08  1.823217e-01
[19]  3.364725e-01  4.700042e-01  5.877875e-01  6.931485e-01
```
But the PMF still doesn't look right.
image

**Comment by hrlai** [comment]
sorry just adding one more thing here: 

`extraDistr::dzinb` uses `dnbinom` in the PMF: https://github.com/twolodzko/extraDistr/blob/a1686f3ce00a3c3c489c0dc6596bc1b351e1fe46/src/zero-inflated-negative-binomial-distribution.cpp#L35

 I think @olivuntu was using the [gamma functions to calculate the same thing](https://mathworld.wolfram.com/BinomialCoefficient.html), but following equation 2 in the [same URL](https://mathworld.wolfram.com/BinomialCoefficient.html), I got the gamma components:
```
      lgamma(x + size) / 
      lgamma(size) / 
      lgamma(x + 1)
```
i.e., without taking `exp`. Not sure if I missed anything.

**Comment by olivuntu** [comment]
Hi @ntierney and @hrlai,

Sorry for being silent lately (off grid ...).
A bit of history and explanation : part of the code for the ZIP (not ZINB) came from the fork of greta by lionel68.
* The ZIP and ZINB are normally defined for discrete random variables, so taking positive integer values (hence not defined for values < `- size` in the ZINB).
* We do need the exponentials in the calculation of the log density if the `lgamma` functions are used, otherwise we could use `gamma(x)` instead of `exp(lgamma(x))`. I think `lgamma` was used for numerical issues.
* Non-finite values are obtained in the log-density for high values of `x + size` (higher than 171 on my machine: `factorial(171)` returns `Inf` locally, as does `exp(710)`). The calculation of the binomial coefficients is problematic for such values. 
* We do need `relu(1 - x)` in the first part of the density, which is 1 when `x` is 0, to account for extra zeros with a probability of `pi_var`. 

Here is a WE which shows that the results are the same with `r_log_prob` and `extraDist::dzinb` expect for `x` values below 0 (actually `x + size`) and over 171.
It seems the issue relates to the numerical limits of `R`, or ?

``` r
pi_var <- 0.2
p <- 0.1
q <- 1 - p
size <- 10

r_log_prob <- function(x) {
  log(
    pi_var * 
      sigmoid::relu(1 - x) + 
      (1 - pi_var) * 
      p^size * 
      q^x * 
      exp(lgamma(x + size)) / 
      exp(lgamma(size)) / 
      exp(lgamma(x + 1))
  )
}

x <- seq(-10, 170, by = 5)
z <- extraDistr::dzinb(x, size = 10, prob= 0.1, pi=0.2)
log(z)
#>  [1]       -Inf       -Inf  -1.609438 -16.173895 -12.868956 -10.745772
#>  [7]  -9.236610  -8.107613  -7.238114  -6.557344  -6.020138  -5.595867
#> [13]  -5.262786  -5.004896  -4.810078  -4.668928  -4.574004  -4.519313
#> [19]  -4.499958  -4.511885  -4.551703  -4.616541  -4.703953  -4.811833
#> [25]  -4.938359  -5.081940  -5.241181  -5.414852  -5.601863  -5.801241
#> [31]  -6.012118  -6.233713  -6.465322  -6.706310  -6.956097  -7.214159
#> [37]  -7.480016
r_log_prob(x)
#>  [1]         NaN   0.1823216  -1.6094379 -16.1738951 -12.8689555 -10.7457717
#>  [7]  -9.2366098  -8.1076125  -7.2381135  -6.5573445  -6.0201384  -5.5958665
#> [13]  -5.2627858  -5.0048963  -4.8100780  -4.6689281  -4.5740040  -4.5193128
#> [19]  -4.4999575  -4.5118852  -4.5517026  -4.6165410  -4.7039529  -4.8118334
#> [25]  -4.9383590  -5.0819398  -5.2411809  -5.4148521  -5.6018626  -5.8012408
#> [31]  -6.0121177  -6.2337128  -6.4653223  -6.7063097  -6.9560974         Inf
#> [37]         Inf
```

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hrlai** [comment]
Thanks for clarifying @olivuntu ! How about taking the `exp` after calculating the log difference of the `lgamma` bunch? See `r_log_prob2` function below. Will this work for you? I'm about to try the ZINB on a dataset so happy to help push this forward.

``` r
pi_var <- 0.2
p <- 0.1
q <- 1 - p
size <- 10

r_log_prob <- function(x) {
  log(
    pi_var * 
      sigmoid::relu(1 - x) + 
      (1 - pi_var) * 
      p^size * 
      q^x * 
      exp(lgamma(x + size)) / 
      exp(lgamma(size)) / 
      exp(lgamma(x + 1))
  )
}

r_log_prob2 <- function(x) {
  log(
    pi_var * 
      sigmoid::relu(1 - x) + 
      (1 - pi_var) * 
      p^size * 
      q^x * 
      exp(lgamma(x + size) - lgamma(size) - lgamma(x + 1))
  )
}

x <- seq(-10, 170, by = 5)
z <- extraDistr::dzinb(x, size = 10, prob= 0.1, pi=0.2, log = TRUE)
z
#>  [1]       -Inf       -Inf  -1.609438 -16.173895 -12.868956 -10.745772
#>  [7]  -9.236610  -8.107613  -7.238114  -6.557344  -6.020138  -5.595867
#> [13]  -5.262786  -5.004896  -4.810078  -4.668928  -4.574004  -4.519313
#> [19]  -4.499958  -4.511885  -4.551703  -4.616541  -4.703953  -4.811833
#> [25]  -4.938359  -5.081940  -5.241181  -5.414852  -5.601863  -5.801241
#> [31]  -6.012118  -6.233713  -6.465322  -6.706310  -6.956097  -7.214159
#> [37]  -7.480016
r_log_prob(x)
#>  [1]         NaN   0.1823216  -1.6094379 -16.1738951 -12.8689555 -10.7457717
#>  [7]  -9.2366098  -8.1076125  -7.2381135  -6.5573445  -6.0201384  -5.5958665
#> [13]  -5.2627858  -5.0048963  -4.8100780  -4.6689281  -4.5740040  -4.5193128
#> [19]  -4.4999575  -4.5118852  -4.5517026  -4.6165410  -4.7039529  -4.8118334
#> [25]  -4.9383590  -5.0819398  -5.2411809  -5.4148521  -5.6018626  -5.8012408
#> [31]  -6.0121177  -6.2337128  -6.4653223  -6.7063097  -6.9560974         Inf
#> [37]         Inf
r_log_prob2(x)
#>  [1]         NaN   0.1823216  -1.6094379 -16.1738951 -12.8689555 -10.7457717
#>  [7]  -9.2366098  -8.1076125  -7.2381135  -6.5573445  -6.0201384  -5.5958665
#> [13]  -5.2627858  -5.0048963  -4.8100780  -4.6689281  -4.5740040  -4.5193128
#> [19]  -4.4999575  -4.5118852  -4.5517026  -4.6165410  -4.7039529  -4.8118334
#> [25]  -4.9383590  -5.0819398  -5.2411809  -5.4148521  -5.6018626  -5.8012408
#> [31]  -6.0121177  -6.2337128  -6.4653223  -6.7063097  -6.9560974  -7.2141594
#> [37]  -7.4800156
```

<sup>Created on 2022-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We still need to fix the density for `x < 0` with should return `-Inf`.

And finally just referencing the `extraDistr` method https://github.com/twolodzko/extraDistr/blob/6cdbe85a98c3a34d8360b8c0ffe6eb78517e0fc3/src/zero-inflated-negative-binomial-distribution.cpp#L18-L37 in case it is helpful later.

**Comment by hrlai** [comment]
So I used @olivuntu 's code in this PR and changed it to be pretty much the same `extraDistr::dzinb` (also directly uses `tfp`'s distribution and bypasses the log Gamma functions entirely --- hopefully more efficient), but don't know how to push the changes without access permission. @njtierney any idea? Sorry not too familiar with Git...

Anyway, here's a reprex. Generating random variates from `greta` and then compare it the the PMF from `extraDistr`. Seems pretty lined up. Any better way to test it?
``` r
library(greta.distributions)
#> Loading required package: greta
#> Warning: package 'greta' was built under R version 4.1.3
#> 
#> Attaching package: 'greta'
#> The following objects are masked from 'package:stats':
#> 
#>     binomial, cov2cor, poisson
#> The following objects are masked from 'package:base':
#> 
#>     %*%, apply, backsolve, beta, chol2inv, colMeans, colSums, diag,
#>     eigen, forwardsolve, gamma, identity, rowMeans, rowSums, sweep,
#>     tapply

foo <- zero_inflated_negative_binomial(1, 0.5, 0.1)
#> i Initialising python and checking dependencies, this may take a moment.
#> v Initialising python and checking dependencies ... done!               
bar <- calculate(foo, nsim = 1e4)

plot(proportions(table(bar$foo)))
lines(0:20, extraDistr::dzinb(0:20, 1, 0.5, 0.1), col = "red")
```



``` r


# another test with more excess zeros
foo <- zero_inflated_negative_binomial(1, 0.5, 0.5)
bar <- calculate(foo, nsim = 1e4)

plot(proportions(table(bar$foo)))
lines(0:20, extraDistr::dzinb(0:20, 1, 0.5, 0.5), col = "red")
```



<sup>Created on 2022-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by njtierney** [comment]
Thanks so much, @hrlai !

OK I think I see a way to do this - based on https://stackoverflow.com/questions/9153598/how-do-i-fetch-a-branch-on-someone-elses-fork-on-github

For this to work I'd recommend working from the command line/terminal/power shell - let me know if you want a hand with any of this, happy to jump on a zoom call or something!

```
git remote add olivuntu https://github.com/olivuntu/greta.distributions
git fetch olivuntu
git checkout -b olivuntu-zip-zinb olivuntu/main
```

Then you should have a copy of their branch and you can make changes on it

Let me know how you go?

**Comment by hrlai** [comment]
Opps, still got permission denied. I think this is because I'm still trying to push to https://github.com/olivuntu/greta.distributions/

By the way, ditto for ZI Poisson and seems working:
image

**Comment by hrlai** [comment]
From the end of [this post](https://tighten.com/blog/adding-commits-to-a-pull-request/) it seems “Allow edits from maintainers” needs to be ticked. Let me know if you're comfortable with this, otherwise I can always just send the codes to you 😃

**Comment by njtierney** [comment]
Hmmm! Are you on your own copy of the greta distributions repo? When making
those changes you should be in your own fork - that way you can push to
your own copy.

**Comment by njtierney** [comment]
If that doesn’t work then I’m more than happy for you send me the code via
email if that’s better for you, but I like the idea of this working via git
🤓

**Comment by hrlai** [comment]
No worries, my bad, all I needed to do after your git instructions above is make sure to push to my own fork `git push origin`. Codes are in PR #17 now.

**Comment by olivuntu** [comment]
Hi @hrlai,
Thanks for your tests and for advancing this  topic ! 
@njtierney, can I be of any help now ? 
Is the permission issue raised earlier solved? 

All the best !

**Pull request closed without merging**
